apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-staging
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-staging
  template:
    metadata:
      labels:
        app: frontend-staging
    spec:
      containers:
        - name: frontend-staging
          image: irwan34/frontend-service:c8f0467a792e8b862db2a7baff3e1c6cd9b1e192
          ports:
            - containerPort: 8000

