apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-api
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-api
  template:
    metadata:
      labels:
        app: myapp-api
    spec:
      containers:
        - name: myapp-api
          image: irwan34/api-service@sha256:afce9d0d30f7f4a32f72545ee0bbcad1290d273b171abfcb5f00f591eaddd840
          ports:
            - containerPort: 8000

