apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-api
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-api
  template:
    metadata:
      labels:
        app: myapp-api
    spec:
      containers:
        - name: myapp-api
          image: irwan34/api-service@sha256:08e7991f4b5e0c1948b44710ec78324a16ab3564340820180151b39123c1930f
          ports:
            - containerPort: 8000

