apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-frontend
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-frontend
  template:
    metadata:
      labels:
        app: myapp-frontend
    spec:
      containers:
        - name: myapp-frontend
          image: irwan34/frontend-service@sha256:de06fa236149af5ee961889138831f9e0163003ba256ded35c6c3b099b9c8a45
          ports:
            - containerPort: 8000

